.model flat
.code

extern _resolve_export@4:proc

; Macro to generate export stubs
PROXY_EXPORT macro name, index
public _&name
_&name proc
    push index
    call _resolve_export@4
    jmp eax
_&name endp
endm

PROXY_EXPORT WINMM_ORD2, 0
PROXY_EXPORT CloseDriver, 1
PROXY_EXPORT DefDriverProc, 2
PROXY_EXPORT DriverCallback, 3
PROXY_EXPORT DrvGetModuleHandle, 4
PROXY_EXPORT GetDriverModuleHandle, 5
PROXY_EXPORT OpenDriver, 6
PROXY_EXPORT PlaySound, 7
PROXY_EXPORT PlaySoundA, 8
PROXY_EXPORT PlaySoundW, 9
PROXY_EXPORT SendDriverMessage, 10
PROXY_EXPORT WOWAppExit, 11
PROXY_EXPORT auxGetDevCapsA, 12
PROXY_EXPORT auxGetDevCapsW, 13
PROXY_EXPORT auxGetNumDevs, 14
PROXY_EXPORT auxGetVolume, 15
PROXY_EXPORT auxOutMessage, 16
PROXY_EXPORT auxSetVolume, 17
PROXY_EXPORT joyConfigChanged, 18
PROXY_EXPORT joyGetDevCapsA, 19
PROXY_EXPORT joyGetDevCapsW, 20
PROXY_EXPORT joyGetNumDevs, 21
PROXY_EXPORT joyGetPos, 22
PROXY_EXPORT joyGetPosEx, 23
PROXY_EXPORT joyGetThreshold, 24
PROXY_EXPORT joyReleaseCapture, 25
PROXY_EXPORT joySetCapture, 26
PROXY_EXPORT joySetThreshold, 27
PROXY_EXPORT mciDriverNotify, 28
PROXY_EXPORT mciDriverYield, 29
PROXY_EXPORT mciExecute, 30
PROXY_EXPORT mciFreeCommandResource, 31
PROXY_EXPORT mciGetCreatorTask, 32
PROXY_EXPORT mciGetDeviceIDA, 33
PROXY_EXPORT mciGetDeviceIDFromElementIDA, 34
PROXY_EXPORT mciGetDeviceIDFromElementIDW, 35
PROXY_EXPORT mciGetDeviceIDW, 36
PROXY_EXPORT mciGetDriverData, 37
PROXY_EXPORT mciGetErrorStringA, 38
PROXY_EXPORT mciGetErrorStringW, 39
PROXY_EXPORT mciGetYieldProc, 40
PROXY_EXPORT mciLoadCommandResource, 41
PROXY_EXPORT mciSendCommandA, 42
PROXY_EXPORT mciSendCommandW, 43
PROXY_EXPORT mciSendStringA, 44
PROXY_EXPORT mciSendStringW, 45
PROXY_EXPORT mciSetDriverData, 46
PROXY_EXPORT mciSetYieldProc, 47
PROXY_EXPORT midiConnect, 48
PROXY_EXPORT midiDisconnect, 49
PROXY_EXPORT midiInAddBuffer, 50
PROXY_EXPORT midiInClose, 51
PROXY_EXPORT midiInGetDevCapsA, 52
PROXY_EXPORT midiInGetDevCapsW, 53
PROXY_EXPORT midiInGetErrorTextA, 54
PROXY_EXPORT midiInGetErrorTextW, 55
PROXY_EXPORT midiInGetID, 56
PROXY_EXPORT midiInGetNumDevs, 57
PROXY_EXPORT midiInMessage, 58
PROXY_EXPORT midiInOpen, 59
PROXY_EXPORT midiInPrepareHeader, 60
PROXY_EXPORT midiInReset, 61
PROXY_EXPORT midiInStart, 62
PROXY_EXPORT midiInStop, 63
PROXY_EXPORT midiInUnprepareHeader, 64
PROXY_EXPORT midiOutCacheDrumPatches, 65
PROXY_EXPORT midiOutCachePatches, 66
PROXY_EXPORT midiOutClose, 67
PROXY_EXPORT midiOutGetDevCapsA, 68
PROXY_EXPORT midiOutGetDevCapsW, 69
PROXY_EXPORT midiOutGetErrorTextA, 70
PROXY_EXPORT midiOutGetErrorTextW, 71
PROXY_EXPORT midiOutGetID, 72
PROXY_EXPORT midiOutGetNumDevs, 73
PROXY_EXPORT midiOutGetVolume, 74
PROXY_EXPORT midiOutLongMsg, 75
PROXY_EXPORT midiOutMessage, 76
PROXY_EXPORT midiOutOpen, 77
PROXY_EXPORT midiOutPrepareHeader, 78
PROXY_EXPORT midiOutReset, 79
PROXY_EXPORT midiOutSetVolume, 80
PROXY_EXPORT midiOutShortMsg, 81
PROXY_EXPORT midiOutUnprepareHeader, 82
PROXY_EXPORT midiStreamClose, 83
PROXY_EXPORT midiStreamOpen, 84
PROXY_EXPORT midiStreamOut, 85
PROXY_EXPORT midiStreamPause, 86
PROXY_EXPORT midiStreamPosition, 87
PROXY_EXPORT midiStreamProperty, 88
PROXY_EXPORT midiStreamRestart, 89
PROXY_EXPORT midiStreamStop, 90
PROXY_EXPORT mixerClose, 91
PROXY_EXPORT mixerGetControlDetailsA, 92
PROXY_EXPORT mixerGetControlDetailsW, 93
PROXY_EXPORT mixerGetDevCapsA, 94
PROXY_EXPORT mixerGetDevCapsW, 95
PROXY_EXPORT mixerGetID, 96
PROXY_EXPORT mixerGetLineControlsA, 97
PROXY_EXPORT mixerGetLineControlsW, 98
PROXY_EXPORT mixerGetLineInfoA, 99
PROXY_EXPORT mixerGetLineInfoW, 100
PROXY_EXPORT mixerGetNumDevs, 101
PROXY_EXPORT mixerMessage, 102
PROXY_EXPORT mixerOpen, 103
PROXY_EXPORT mixerSetControlDetails, 104
PROXY_EXPORT mmDrvInstall, 105
PROXY_EXPORT mmGetCurrentTask, 106
PROXY_EXPORT mmTaskBlock, 107
PROXY_EXPORT mmTaskCreate, 108
PROXY_EXPORT mmTaskSignal, 109
PROXY_EXPORT mmTaskYield, 110
PROXY_EXPORT mmioAdvance, 111
PROXY_EXPORT mmioAscend, 112
PROXY_EXPORT mmioClose, 113
PROXY_EXPORT mmioCreateChunk, 114
PROXY_EXPORT mmioDescend, 115
PROXY_EXPORT mmioFlush, 116
PROXY_EXPORT mmioGetInfo, 117
PROXY_EXPORT mmioInstallIOProcA, 118
PROXY_EXPORT mmioInstallIOProcW, 119
PROXY_EXPORT mmioOpenA, 120
PROXY_EXPORT mmioOpenW, 121
PROXY_EXPORT mmioRead, 122
PROXY_EXPORT mmioRenameA, 123
PROXY_EXPORT mmioRenameW, 124
PROXY_EXPORT mmioSeek, 125
PROXY_EXPORT mmioSendMessage, 126
PROXY_EXPORT mmioSetBuffer, 127
PROXY_EXPORT mmioSetInfo, 128
PROXY_EXPORT mmioStringToFOURCCA, 129
PROXY_EXPORT mmioStringToFOURCCW, 130
PROXY_EXPORT mmioWrite, 131
PROXY_EXPORT mmsystemGetVersion, 132
PROXY_EXPORT sndPlaySoundA, 133
PROXY_EXPORT sndPlaySoundW, 134
PROXY_EXPORT timeBeginPeriod, 135
PROXY_EXPORT timeEndPeriod, 136
PROXY_EXPORT timeGetDevCaps, 137
PROXY_EXPORT timeGetSystemTime, 138
PROXY_EXPORT timeGetTime, 139
PROXY_EXPORT timeKillEvent, 140
PROXY_EXPORT timeSetEvent, 141
PROXY_EXPORT waveInAddBuffer, 142
PROXY_EXPORT waveInClose, 143
PROXY_EXPORT waveInGetDevCapsA, 144
PROXY_EXPORT waveInGetDevCapsW, 145
PROXY_EXPORT waveInGetErrorTextA, 146
PROXY_EXPORT waveInGetErrorTextW, 147
PROXY_EXPORT waveInGetID, 148
PROXY_EXPORT waveInGetNumDevs, 149
PROXY_EXPORT waveInGetPosition, 150
PROXY_EXPORT waveInMessage, 151
PROXY_EXPORT waveInOpen, 152
PROXY_EXPORT waveInPrepareHeader, 153
PROXY_EXPORT waveInReset, 154
PROXY_EXPORT waveInStart, 155
PROXY_EXPORT waveInStop, 156
PROXY_EXPORT waveInUnprepareHeader, 157
PROXY_EXPORT waveOutBreakLoop, 158
PROXY_EXPORT waveOutClose, 159
PROXY_EXPORT waveOutGetDevCapsA, 160
PROXY_EXPORT waveOutGetDevCapsW, 161
PROXY_EXPORT waveOutGetErrorTextA, 162
PROXY_EXPORT waveOutGetErrorTextW, 163
PROXY_EXPORT waveOutGetID, 164
PROXY_EXPORT waveOutGetNumDevs, 165
PROXY_EXPORT waveOutGetPitch, 166
PROXY_EXPORT waveOutGetPlaybackRate, 167
PROXY_EXPORT waveOutGetPosition, 168
PROXY_EXPORT waveOutGetVolume, 169
PROXY_EXPORT waveOutMessage, 170
PROXY_EXPORT waveOutOpen, 171
PROXY_EXPORT waveOutPause, 172
PROXY_EXPORT waveOutPrepareHeader, 173
PROXY_EXPORT waveOutReset, 174
PROXY_EXPORT waveOutRestart, 175
PROXY_EXPORT waveOutSetPitch, 176
PROXY_EXPORT waveOutSetPlaybackRate, 177
PROXY_EXPORT waveOutSetVolume, 178
PROXY_EXPORT waveOutUnprepareHeader, 179
PROXY_EXPORT waveOutWrite, 180
PROXY_EXPORT NotifyCallbackData, 181
PROXY_EXPORT WOW32DriverCallback, 182
PROXY_EXPORT WOW32ResolveMultiMediaHandle, 183
PROXY_EXPORT aux32Message, 184
PROXY_EXPORT joy32Message, 185
PROXY_EXPORT mci32Message, 186
PROXY_EXPORT mid32Message, 187
PROXY_EXPORT mod32Message, 188
PROXY_EXPORT mxd32Message, 189
PROXY_EXPORT tid32Message, 190
PROXY_EXPORT wid32Message, 191
PROXY_EXPORT wod32Message, 192

end
